website_pairs = {
    'Khan Academy': 'khanacademy.org',
    'Project Gutenberg': 'gutenberg.org',
    'MIT OpenCourseWare': 'ocw.mit.edu',
    'OpenStax': 'openstax.org',
    'Internet Archive': 'archive.org',
    'Python Docs': 'docs.python.org',
    'C++ Docs': 'cplusplus.com',
    'Java Docs': 'docs.oracle.com',
    'JavaScript Docs': 'developer.mozilla.org',
    'Flutter Docs': 'flutter.dev',
    'StackOverflow': 'stackoverflow.com',
    'PubMed': 'pubmed.ncbi.nlm.nih.gov',
    'ArXiv': 'arxiv.org',
    'WHO': 'who.int',
    'CDC': 'cdc.gov',
    'Associated Press': 'apnews.com',
    'Reuters': 'reuters.com',
    'BBC News': 'bbc.com',
    'The Guardian': 'theguardian.com',
    'Data.gov': 'data.gov',
    'Census Bureau': 'census.gov',
    'Google Dataset Search': 'datasetsearch.research.google.com',
    'EU Open Data Portal': 'data.europa.eu',
    'NASA\'s Data Portal': 'data.nasa.gov'
}
